# Runs a gradle build for the entire project, and then runs all unit tests.

name: build & test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Gradle build
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          # Unfortunately we have to set this explicitly per module for now (see https://github.com/paambaati/codeclimate-action/issues/208)
          JACOCO_SOURCE_PATH: ${{github.workspace}}/bot/src/main/kotlin ${{github.workspace}}/lootsplit-domain/src/main/kotlin ${{github.workspace}}/infra-string-ext/src/main/kotlin
        with:
          coverageCommand: ./gradlew koverMergedXmlReport
          coverageLocations: ${{github.workspace}}/build/kover/coverage.xml:jacoco